import express from 'express'; // express is a function
import config from 'config'; // config is a function
import { logging } from './startup/logging.js';
import { logger } from './startup/logging.js';
import db from './startup/db.js';
import routes from './startup/routes.js';
import configuration from './startup/configuration.js';

// StartUp
const app = express();
logging();
configuration();
db();
routes(app);

// according to the environmnet (development - production)
console.log(`Application Name: ${config.get('name')}`);
console.log(`Mail Server: ${config.get('mail.host')}`);

// set PORT and Server Listening
const port = process.env.port || 3000;
app.listen(port, () => logger.info(`Listening on port ${port}...`));


/* ****** Object ID ********* */
// generated by mongoDB Driver
// _id: 61900e5dddea3ba424f58f51 (24)
// every two characters is a byte (12 bytes)
// 4 bytes: timestamp
// 3 bytes: machine identifier
// 2 bytes: process identifier
// 3 bytes: counter

// 2 ^ 24 = 16M (that can overflow)


/* ****** request pipeline cycle ********* */
// 1- Parse the JSON body (JSON or urlencoded)
// 2- Authorization
// 3- Admin
// 4- Async Middleware  . Route Handler 
//                      . Error Handler


